---
title: "Data Organization"
format: html
editor: visual
---

### data

-   \_raw: Directory inside data, containing your raw data file(s), which must never be edited

-   raw_data.xlsx: This need not necessarily be an Excel-file, but should be seen as a placeholder for whichever raw data, your project is based on

-   01_dat_load.tsv: Your loaded data, e.g. combining multiple sheets from an excel file

-   02_dat_clean.tsv: Your data cleaned per your specifications and in tidy format

-   03_dat_aug.tsv: Your data with added variables, e.g. like computing a BMI

    ### R

-   01_load.qmd: Loads your data, e.g. combining multiple sheets from an excel file

-   02_clean.qmd: Cleans your data per your specifications and converts to tidy format

-   03_augment.qmd: Adds new variables, like e.g. computing a BMI

-   04_describe.qmd: Descriptive statistics, how many in each group, etc.

-   05_analysis_1.qmd: Here goes your first analysis

-   06_analysis_2.qmd: Here goes your second analysis and so on

-   99_proj_func.qmd: DRY: Don’t Repeat Yourself, repeated code goes into a function

-   00_all.qmd: The master document, capable of running the entire project in one go

    ### results

-   *\*.html: The output from your* .qmds in your R-directory

-   key_plots.png: Whichever of all the nice plots you made, which should end up in your final presentation

    ### doc

-   presentation.qmd: Your final Quarto Presentation of your project

-   presentation.html: Self-contained HTML5 presentation (just as the course slides)
