---
title: "Group 11 - Gene expression in colorectal cancer"
author: "Eleni-Sofia Tseperi (s240066),	Johanne Lund	(s233246), Marie Picquet	(s233736), Eglantine Anton	(s233242), Qiuyan Wu	(s241063)"
format:
  revealjs:
    code-line-numbers: true
    scrollable: true
    smaller: true
    scoll: true
    theme: night
    transition: slide
    incremental: true 
editor: visual
---

```{r}
library(tidyverse)
library(here)
library(readr)
library(broom)
library(here)
library(ggrepel)
```

## Introduction

-   Background

    -   Colorectal cancer (CRC) is a major cause of cancer mortality

    -   Gene expression analysis can help identify dysregulated genes

-   Goal of the project

    -   Investigate xxx

    -   Model xxx

-   Data sets

    -   Gene expression level for 1935 genes

    -   Patient information for 62 patients

    -   Artificially made dirty and messy to increase the difficulty of the projects

## Methods overview

(incl run-all file), raw, load, making dirty

## Methods - Tidy, clean & augment

### Tidy

::: columns
::: {.column width="50%"}
Expression data

-   The columns represent observations and the rows variables
    -   Pivot the data set
:::

::: {.column width="50%"}
Patient data

-   `DFS event/Adj_Radio/Adj_Chem` contains 3 variables

    -   Separate it into 3 distinct variables

-   Observations of column `DFS (in years and months)` contains two values

    -   Convert into months to have only value per observation
:::
:::

### Clean

Combine the two data sets by joining on the patient ID.

-   Missing values "N/A" and "NA"

    -   Load everything as NA when opening the file

-   Gender as "Male", "M", "Female", "F"

    -   Convert M to Male and F to Female

-   One patient has an Age \< 0

    -   Substitute it by the mean value of the age of the other observations

-   Long column names with several words

    -   Remove "gene\_" at the beginning of all the gene names

    -   Remove the units from the names

    -   Replace spaces by \_

### Augment

-   Create an age group variable

-   Create a metastasis variable

    -   Duke stage A, B, C don't involve metastasis

    -   Duke stage D involve metastasis

## Methods - Describe

## Results - Data description

## Methods - Analysis 1

## Methods - Analysis 2

## Methods - Analysis 3

## Results - Analysis 1 & 2

## Results - Analysis 3 & discussion
