## Load libraries

```{r}
#| message: false
library(readr)
library(tidyverse)
```

## Data describe

```{r}
project_path <- "~/projects/group_11_project/"
data <- read_tsv(str_c(project_path, "/data/02_dat_clean.tsv"))
```

```{r}

# Check for missing values
sum(is.na(data))  # Total number of NA values in the dataset
```

Age and DFS 'Simple statistics

The relationship between age and DFS

```{r}
# Define a vector of numeric feature names
features_num <- c("Age", "DFS")
# Select numeric columns based on features_num
numeric_data <- data[ , features_num, drop = FALSE]


# Compute summary statistics for each numeric feature
summary_stats <- numeric_data |>
  summarise(across(everything(), list(
    min = min,
    max = max,
    mean = mean,
    sd = sd
  ), na.rm = TRUE))

#Format the summary statistics into a table
summary_table_long <- summary_stats %>%
  pivot_longer(
    cols = everything(),
    names_to = c("Feature", "Statistic"),
    names_sep = "_",
    values_to = "Value"
  ) %>%
  arrange(Feature, Statistic)

#Transform back to wide format
summary_table_wide <- summary_table_long %>%
  pivot_wider(
    names_from = Statistic,
    values_from = Value
  )

# Print the wide table
print(summary_table_wide)
```

Inspect the dataset:

```{r}
data
```
```{r}
library(ggplot2)

ggplot(numeric_data, aes(x = Age, y = DFS)) +
  geom_point() +               # Scatter plot
  labs(
    title = "DFS vs Age",       # Plot title
    x = "Age",                  # X-axis label
    y = "DFS (months)"          # Y-axis label
  ) +
  theme_minimal() +             # Clean theme
  theme(
    panel.grid.major = element_line(color = "grey", size = 0.5),  # Grid lines
    panel.grid.minor = element_line(color = "grey", size = 0.25)
  )
```

The final dataframe contains 62 observations(rows) which are described by 64 variables.

```{r}
patient_data
```
